(function (factory) {
    if (typeof module === "object" && typeof module.exports === "object") {
        var v = factory(require, exports);
        if (v !== undefined) module.exports = v;
    }
    else if (typeof define === "function" && define.amd) {
        define(["require", "exports", "./Types"], factory);
    }
})(function (require, exports) {
    "use strict";
    exports.__esModule = true;
    // Generated automatically by nearley
    // http://github.com/Hardmath123/nearley
    function id(d) { return d[0]; }
    var Types_1 = require("./Types");
    ;
    ;
    exports.grammar = {
        ParserRules: [
            { "name": "main$ebnf$1", "symbols": ["will_you"], "postprocess": id },
            { "name": "main$ebnf$1", "symbols": [], "postprocess": function (d) { return null; } },
            { "name": "main$ebnf$2", "symbols": ["please"], "postprocess": id },
            { "name": "main$ebnf$2", "symbols": [], "postprocess": function (d) { return null; } },
            { "name": "main$ebnf$3", "symbols": ["please"], "postprocess": id },
            { "name": "main$ebnf$3", "symbols": [], "postprocess": function (d) { return null; } },
            { "name": "main", "symbols": ["main$ebnf$1", "main$ebnf$2", "command", "main$ebnf$3"], "postprocess": function (d) { return d[2]; } },
            { "name": "command", "symbols": ["take", "entity"], "postprocess": function (d) { return new Types_1.TakeCommand(d[1]); } },
            { "name": "command", "symbols": ["move", "it", "location"], "postprocess": function (d) { return new Types_1.DropCommand(d[2]); } },
            { "name": "command", "symbols": ["move", "entity", "location"], "postprocess": function (d) { return new Types_1.MoveCommand(d[1], d[2]); } },
            { "name": "location", "symbols": ["relation", "entity"], "postprocess": function (d) { return new Types_1.Location(d[0], d[1]); } },
            { "name": "entity", "symbols": ["quantifierSG", "simpleObjectSG"], "postprocess": function (d) { return new Types_1.Entity(d[0], d[1]); } },
            { "name": "entity", "symbols": ["quantifierSG", "relativeObjectSG"], "postprocess": function (d) { return new Types_1.Entity(d[0], d[1]); } },
            { "name": "entity", "symbols": ["quantifierPL", "simpleObjectPL"], "postprocess": function (d) { return new Types_1.Entity(d[0], d[1]); } },
            { "name": "entity", "symbols": ["quantifierPL", "relativeObjectPL"], "postprocess": function (d) { return new Types_1.Entity(d[0], d[1]); } },
            { "name": "relativeObjectSG$ebnf$1", "symbols": ["that_is"], "postprocess": id },
            { "name": "relativeObjectSG$ebnf$1", "symbols": [], "postprocess": function (d) { return null; } },
            { "name": "relativeObjectSG", "symbols": ["simpleObjectSG", "relativeObjectSG$ebnf$1", "location"], "postprocess": function (d) { return new Types_1.RelativeObject(d[0], d[2]); } },
            { "name": "relativeObjectPL$ebnf$1", "symbols": ["that_are"], "postprocess": id },
            { "name": "relativeObjectPL$ebnf$1", "symbols": [], "postprocess": function (d) { return null; } },
            { "name": "relativeObjectPL", "symbols": ["simpleObjectPL", "relativeObjectPL$ebnf$1", "location"], "postprocess": function (d) { return new Types_1.RelativeObject(d[0], d[2]); } },
            { "name": "simpleObjectSG$ebnf$1", "symbols": ["size"], "postprocess": id },
            { "name": "simpleObjectSG$ebnf$1", "symbols": [], "postprocess": function (d) { return null; } },
            { "name": "simpleObjectSG$ebnf$2", "symbols": ["color"], "postprocess": id },
            { "name": "simpleObjectSG$ebnf$2", "symbols": [], "postprocess": function (d) { return null; } },
            { "name": "simpleObjectSG", "symbols": ["simpleObjectSG$ebnf$1", "simpleObjectSG$ebnf$2", "formSG"], "postprocess": function (d) { return new Types_1.SimpleObject(d[0], d[1], d[2]); } },
            { "name": "simpleObjectPL$ebnf$1", "symbols": ["size"], "postprocess": id },
            { "name": "simpleObjectPL$ebnf$1", "symbols": [], "postprocess": function (d) { return null; } },
            { "name": "simpleObjectPL$ebnf$2", "symbols": ["color"], "postprocess": id },
            { "name": "simpleObjectPL$ebnf$2", "symbols": [], "postprocess": function (d) { return null; } },
            { "name": "simpleObjectPL", "symbols": ["simpleObjectPL$ebnf$1", "simpleObjectPL$ebnf$2", "formPL"], "postprocess": function (d) { return new Types_1.SimpleObject(d[0], d[1], d[2]); } },
            { "name": "quantifierSG$subexpression$1$string$1", "symbols": [{ "literal": "a" }, { "literal": "n" }, { "literal": "y" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "quantifierSG$subexpression$1", "symbols": ["quantifierSG$subexpression$1$string$1"] },
            { "name": "quantifierSG$subexpression$1$string$2", "symbols": [{ "literal": "a" }, { "literal": "n" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "quantifierSG$subexpression$1", "symbols": ["quantifierSG$subexpression$1$string$2"] },
            { "name": "quantifierSG$subexpression$1", "symbols": [{ "literal": "a" }] },
            { "name": "quantifierSG", "symbols": ["quantifierSG$subexpression$1"], "postprocess": function (d) { return "any"; } },
            { "name": "quantifierSG$subexpression$2$string$1", "symbols": [{ "literal": "t" }, { "literal": "h" }, { "literal": "e" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "quantifierSG$subexpression$2", "symbols": ["quantifierSG$subexpression$2$string$1"] },
            { "name": "quantifierSG", "symbols": ["quantifierSG$subexpression$2"], "postprocess": function (d) { return "the"; } },
            { "name": "quantifierSG$subexpression$3$string$1", "symbols": [{ "literal": "e" }, { "literal": "v" }, { "literal": "e" }, { "literal": "r" }, { "literal": "y" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "quantifierSG$subexpression$3", "symbols": ["quantifierSG$subexpression$3$string$1"] },
            { "name": "quantifierSG", "symbols": ["quantifierSG$subexpression$3"], "postprocess": function (d) { return "all"; } },
            { "name": "quantifierPL$subexpression$1$string$1", "symbols": [{ "literal": "a" }, { "literal": "l" }, { "literal": "l" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "quantifierPL$subexpression$1", "symbols": ["quantifierPL$subexpression$1$string$1"] },
            { "name": "quantifierPL", "symbols": ["quantifierPL$subexpression$1"], "postprocess": function (d) { return "all"; } },
            { "name": "relation$subexpression$1$string$1", "symbols": [{ "literal": "l" }, { "literal": "e" }, { "literal": "f" }, { "literal": "t" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "relation$subexpression$1$string$2", "symbols": [{ "literal": "o" }, { "literal": "f" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "relation$subexpression$1", "symbols": ["relation$subexpression$1$string$1", "relation$subexpression$1$string$2"] },
            { "name": "relation$subexpression$1$string$3", "symbols": [{ "literal": "t" }, { "literal": "o" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "relation$subexpression$1$string$4", "symbols": [{ "literal": "t" }, { "literal": "h" }, { "literal": "e" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "relation$subexpression$1$string$5", "symbols": [{ "literal": "l" }, { "literal": "e" }, { "literal": "f" }, { "literal": "t" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "relation$subexpression$1$string$6", "symbols": [{ "literal": "o" }, { "literal": "f" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "relation$subexpression$1", "symbols": ["relation$subexpression$1$string$3", "relation$subexpression$1$string$4", "relation$subexpression$1$string$5", "relation$subexpression$1$string$6"] },
            { "name": "relation", "symbols": ["relation$subexpression$1"], "postprocess": function (d) { return "leftof"; } },
            { "name": "relation$subexpression$2$string$1", "symbols": [{ "literal": "r" }, { "literal": "i" }, { "literal": "g" }, { "literal": "h" }, { "literal": "t" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "relation$subexpression$2$string$2", "symbols": [{ "literal": "o" }, { "literal": "f" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "relation$subexpression$2", "symbols": ["relation$subexpression$2$string$1", "relation$subexpression$2$string$2"] },
            { "name": "relation$subexpression$2$string$3", "symbols": [{ "literal": "t" }, { "literal": "o" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "relation$subexpression$2$string$4", "symbols": [{ "literal": "t" }, { "literal": "h" }, { "literal": "e" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "relation$subexpression$2$string$5", "symbols": [{ "literal": "r" }, { "literal": "i" }, { "literal": "g" }, { "literal": "h" }, { "literal": "t" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "relation$subexpression$2$string$6", "symbols": [{ "literal": "o" }, { "literal": "f" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "relation$subexpression$2", "symbols": ["relation$subexpression$2$string$3", "relation$subexpression$2$string$4", "relation$subexpression$2$string$5", "relation$subexpression$2$string$6"] },
            { "name": "relation", "symbols": ["relation$subexpression$2"], "postprocess": function (d) { return "rightof"; } },
            { "name": "relation$subexpression$3$string$1", "symbols": [{ "literal": "i" }, { "literal": "n" }, { "literal": "s" }, { "literal": "i" }, { "literal": "d" }, { "literal": "e" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "relation$subexpression$3", "symbols": ["relation$subexpression$3$string$1"] },
            { "name": "relation$subexpression$3$string$2", "symbols": [{ "literal": "i" }, { "literal": "n" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "relation$subexpression$3", "symbols": ["relation$subexpression$3$string$2"] },
            { "name": "relation$subexpression$3$string$3", "symbols": [{ "literal": "i" }, { "literal": "n" }, { "literal": "t" }, { "literal": "o" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "relation$subexpression$3", "symbols": ["relation$subexpression$3$string$3"] },
            { "name": "relation", "symbols": ["relation$subexpression$3"], "postprocess": function (d) { return "inside"; } },
            { "name": "relation$subexpression$4$string$1", "symbols": [{ "literal": "o" }, { "literal": "n" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "relation$subexpression$4", "symbols": ["relation$subexpression$4$string$1"] },
            { "name": "relation$subexpression$4$string$2", "symbols": [{ "literal": "o" }, { "literal": "n" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "relation$subexpression$4$string$3", "symbols": [{ "literal": "t" }, { "literal": "o" }, { "literal": "p" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "relation$subexpression$4$string$4", "symbols": [{ "literal": "o" }, { "literal": "f" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "relation$subexpression$4", "symbols": ["relation$subexpression$4$string$2", "relation$subexpression$4$string$3", "relation$subexpression$4$string$4"] },
            { "name": "relation", "symbols": ["relation$subexpression$4"], "postprocess": function (d) { return "ontop"; } },
            { "name": "relation$subexpression$5$string$1", "symbols": [{ "literal": "u" }, { "literal": "n" }, { "literal": "d" }, { "literal": "e" }, { "literal": "r" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "relation$subexpression$5", "symbols": ["relation$subexpression$5$string$1"] },
            { "name": "relation$subexpression$5$string$2", "symbols": [{ "literal": "b" }, { "literal": "e" }, { "literal": "l" }, { "literal": "o" }, { "literal": "w" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "relation$subexpression$5", "symbols": ["relation$subexpression$5$string$2"] },
            { "name": "relation", "symbols": ["relation$subexpression$5"], "postprocess": function (d) { return "under"; } },
            { "name": "relation$subexpression$6$string$1", "symbols": [{ "literal": "b" }, { "literal": "e" }, { "literal": "s" }, { "literal": "i" }, { "literal": "d" }, { "literal": "e" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "relation$subexpression$6", "symbols": ["relation$subexpression$6$string$1"] },
            { "name": "relation", "symbols": ["relation$subexpression$6"], "postprocess": function (d) { return "beside"; } },
            { "name": "relation$subexpression$7$string$1", "symbols": [{ "literal": "a" }, { "literal": "b" }, { "literal": "o" }, { "literal": "v" }, { "literal": "e" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "relation$subexpression$7", "symbols": ["relation$subexpression$7$string$1"] },
            { "name": "relation", "symbols": ["relation$subexpression$7"], "postprocess": function (d) { return "above"; } },
            { "name": "relation$subexpression$8$string$1", "symbols": [{ "literal": "b" }, { "literal": "e" }, { "literal": "h" }, { "literal": "i" }, { "literal": "n" }, { "literal": "d" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "relation$subexpression$8", "symbols": ["relation$subexpression$8$string$1"] },
            { "name": "relation$subexpression$8$string$2", "symbols": [{ "literal": "i" }, { "literal": "n" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "relation$subexpression$8$string$3", "symbols": [{ "literal": "b" }, { "literal": "a" }, { "literal": "c" }, { "literal": "k" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "relation$subexpression$8$string$4", "symbols": [{ "literal": "o" }, { "literal": "f" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "relation$subexpression$8", "symbols": ["relation$subexpression$8$string$2", "relation$subexpression$8$string$3", "relation$subexpression$8$string$4"] },
            { "name": "relation$subexpression$8$string$5", "symbols": [{ "literal": "t" }, { "literal": "o" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "relation$subexpression$8$string$6", "symbols": [{ "literal": "t" }, { "literal": "h" }, { "literal": "e" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "relation$subexpression$8$string$7", "symbols": [{ "literal": "b" }, { "literal": "a" }, { "literal": "c" }, { "literal": "k" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "relation$subexpression$8$string$8", "symbols": [{ "literal": "o" }, { "literal": "f" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "relation$subexpression$8", "symbols": ["relation$subexpression$8$string$5", "relation$subexpression$8$string$6", "relation$subexpression$8$string$7", "relation$subexpression$8$string$8"] },
            { "name": "relation", "symbols": ["relation$subexpression$8"], "postprocess": function (d) { return "behind"; } },
            { "name": "relation$subexpression$9$string$1", "symbols": [{ "literal": "b" }, { "literal": "e" }, { "literal": "f" }, { "literal": "o" }, { "literal": "r" }, { "literal": "e" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "relation$subexpression$9", "symbols": ["relation$subexpression$9$string$1"] },
            { "name": "relation$subexpression$9$string$2", "symbols": [{ "literal": "i" }, { "literal": "n" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "relation$subexpression$9$string$3", "symbols": [{ "literal": "f" }, { "literal": "r" }, { "literal": "o" }, { "literal": "n" }, { "literal": "t" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "relation$subexpression$9$string$4", "symbols": [{ "literal": "o" }, { "literal": "f" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "relation$subexpression$9", "symbols": ["relation$subexpression$9$string$2", "relation$subexpression$9$string$3", "relation$subexpression$9$string$4"] },
            { "name": "relation$subexpression$9$string$5", "symbols": [{ "literal": "t" }, { "literal": "o" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "relation$subexpression$9$string$6", "symbols": [{ "literal": "t" }, { "literal": "h" }, { "literal": "e" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "relation$subexpression$9$string$7", "symbols": [{ "literal": "f" }, { "literal": "r" }, { "literal": "o" }, { "literal": "n" }, { "literal": "t" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "relation$subexpression$9$string$8", "symbols": [{ "literal": "o" }, { "literal": "f" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "relation$subexpression$9", "symbols": ["relation$subexpression$9$string$5", "relation$subexpression$9$string$6", "relation$subexpression$9$string$7", "relation$subexpression$9$string$8"] },
            { "name": "relation", "symbols": ["relation$subexpression$9"], "postprocess": function (d) { return "before"; } },
            { "name": "size$subexpression$1$string$1", "symbols": [{ "literal": "s" }, { "literal": "m" }, { "literal": "a" }, { "literal": "l" }, { "literal": "l" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "size$subexpression$1", "symbols": ["size$subexpression$1$string$1"] },
            { "name": "size$subexpression$1$string$2", "symbols": [{ "literal": "t" }, { "literal": "i" }, { "literal": "n" }, { "literal": "y" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "size$subexpression$1", "symbols": ["size$subexpression$1$string$2"] },
            { "name": "size", "symbols": ["size$subexpression$1"], "postprocess": function (d) { return "small"; } },
            { "name": "size$subexpression$2$string$1", "symbols": [{ "literal": "l" }, { "literal": "a" }, { "literal": "r" }, { "literal": "g" }, { "literal": "e" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "size$subexpression$2", "symbols": ["size$subexpression$2$string$1"] },
            { "name": "size$subexpression$2$string$2", "symbols": [{ "literal": "b" }, { "literal": "i" }, { "literal": "g" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "size$subexpression$2", "symbols": ["size$subexpression$2$string$2"] },
            { "name": "size", "symbols": ["size$subexpression$2"], "postprocess": function (d) { return "large"; } },
            { "name": "color$string$1", "symbols": [{ "literal": "b" }, { "literal": "l" }, { "literal": "a" }, { "literal": "c" }, { "literal": "k" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "color", "symbols": ["color$string$1"], "postprocess": function (d) { return "black"; } },
            { "name": "color$string$2", "symbols": [{ "literal": "w" }, { "literal": "h" }, { "literal": "i" }, { "literal": "t" }, { "literal": "e" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "color", "symbols": ["color$string$2"], "postprocess": function (d) { return "white"; } },
            { "name": "color$string$3", "symbols": [{ "literal": "b" }, { "literal": "l" }, { "literal": "u" }, { "literal": "e" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "color", "symbols": ["color$string$3"], "postprocess": function (d) { return "blue"; } },
            { "name": "color$string$4", "symbols": [{ "literal": "g" }, { "literal": "r" }, { "literal": "e" }, { "literal": "e" }, { "literal": "n" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "color", "symbols": ["color$string$4"], "postprocess": function (d) { return "green"; } },
            { "name": "color$string$5", "symbols": [{ "literal": "y" }, { "literal": "e" }, { "literal": "l" }, { "literal": "l" }, { "literal": "o" }, { "literal": "w" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "color", "symbols": ["color$string$5"], "postprocess": function (d) { return "yellow"; } },
            { "name": "color$string$6", "symbols": [{ "literal": "r" }, { "literal": "e" }, { "literal": "d" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "color", "symbols": ["color$string$6"], "postprocess": function (d) { return "red"; } },
            { "name": "formSG", "symbols": ["form"], "postprocess": function (d) { return d[0]; } },
            { "name": "formPL", "symbols": ["form", { "literal": "s" }], "postprocess": function (d) { return d[0]; } },
            { "name": "formSG$string$1", "symbols": [{ "literal": "b" }, { "literal": "o" }, { "literal": "x" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "formSG", "symbols": ["formSG$string$1"], "postprocess": function (d) { return "box"; } },
            { "name": "formPL$string$1", "symbols": [{ "literal": "b" }, { "literal": "o" }, { "literal": "x" }, { "literal": "e" }, { "literal": "s" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "formPL", "symbols": ["formPL$string$1"], "postprocess": function (d) { return "box"; } },
            { "name": "form$subexpression$1$string$1", "symbols": [{ "literal": "o" }, { "literal": "b" }, { "literal": "j" }, { "literal": "e" }, { "literal": "c" }, { "literal": "t" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "form$subexpression$1", "symbols": ["form$subexpression$1$string$1"] },
            { "name": "form$subexpression$1$string$2", "symbols": [{ "literal": "t" }, { "literal": "h" }, { "literal": "i" }, { "literal": "n" }, { "literal": "g" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "form$subexpression$1", "symbols": ["form$subexpression$1$string$2"] },
            { "name": "form$subexpression$1$string$3", "symbols": [{ "literal": "f" }, { "literal": "o" }, { "literal": "r" }, { "literal": "m" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "form$subexpression$1", "symbols": ["form$subexpression$1$string$3"] },
            { "name": "form", "symbols": ["form$subexpression$1"], "postprocess": function (d) { return "anyform"; } },
            { "name": "form$string$1", "symbols": [{ "literal": "b" }, { "literal": "r" }, { "literal": "i" }, { "literal": "c" }, { "literal": "k" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "form", "symbols": ["form$string$1"], "postprocess": function (d) { return "brick"; } },
            { "name": "form$string$2", "symbols": [{ "literal": "p" }, { "literal": "l" }, { "literal": "a" }, { "literal": "n" }, { "literal": "k" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "form", "symbols": ["form$string$2"], "postprocess": function (d) { return "plank"; } },
            { "name": "form$string$3", "symbols": [{ "literal": "b" }, { "literal": "a" }, { "literal": "l" }, { "literal": "l" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "form", "symbols": ["form$string$3"], "postprocess": function (d) { return "ball"; } },
            { "name": "form$string$4", "symbols": [{ "literal": "p" }, { "literal": "y" }, { "literal": "r" }, { "literal": "a" }, { "literal": "m" }, { "literal": "i" }, { "literal": "d" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "form", "symbols": ["form$string$4"], "postprocess": function (d) { return "pyramid"; } },
            { "name": "form$string$5", "symbols": [{ "literal": "t" }, { "literal": "a" }, { "literal": "b" }, { "literal": "l" }, { "literal": "e" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "form", "symbols": ["form$string$5"], "postprocess": function (d) { return "table"; } },
            { "name": "form$string$6", "symbols": [{ "literal": "c" }, { "literal": "u" }, { "literal": "p" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "form", "symbols": ["form$string$6"], "postprocess": function (d) { return "cup"; } },
            { "name": "form$string$7", "symbols": [{ "literal": "f" }, { "literal": "l" }, { "literal": "o" }, { "literal": "o" }, { "literal": "r" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "form", "symbols": ["form$string$7"], "postprocess": function (d) { return "floor"; } },
            { "name": "take$string$1", "symbols": [{ "literal": "t" }, { "literal": "a" }, { "literal": "k" }, { "literal": "e" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "take", "symbols": ["take$string$1"] },
            { "name": "take$string$2", "symbols": [{ "literal": "g" }, { "literal": "r" }, { "literal": "a" }, { "literal": "s" }, { "literal": "p" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "take", "symbols": ["take$string$2"] },
            { "name": "take$string$3", "symbols": [{ "literal": "p" }, { "literal": "i" }, { "literal": "c" }, { "literal": "k" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "take$string$4", "symbols": [{ "literal": "u" }, { "literal": "p" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "take", "symbols": ["take$string$3", "take$string$4"] },
            { "name": "move$string$1", "symbols": [{ "literal": "m" }, { "literal": "o" }, { "literal": "v" }, { "literal": "e" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "move", "symbols": ["move$string$1"] },
            { "name": "move$string$2", "symbols": [{ "literal": "p" }, { "literal": "u" }, { "literal": "t" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "move", "symbols": ["move$string$2"] },
            { "name": "move$string$3", "symbols": [{ "literal": "d" }, { "literal": "r" }, { "literal": "o" }, { "literal": "p" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "move", "symbols": ["move$string$3"] },
            { "name": "it$string$1", "symbols": [{ "literal": "i" }, { "literal": "t" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "it", "symbols": ["it$string$1"] },
            { "name": "that_is$string$1", "symbols": [{ "literal": "t" }, { "literal": "h" }, { "literal": "a" }, { "literal": "t" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "that_is$string$2", "symbols": [{ "literal": "i" }, { "literal": "s" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "that_is", "symbols": ["that_is$string$1", "that_is$string$2"] },
            { "name": "that_are$string$1", "symbols": [{ "literal": "t" }, { "literal": "h" }, { "literal": "a" }, { "literal": "t" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "that_are$string$2", "symbols": [{ "literal": "a" }, { "literal": "r" }, { "literal": "e" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "that_are", "symbols": ["that_are$string$1", "that_are$string$2"] },
            { "name": "will_you$subexpression$1$string$1", "symbols": [{ "literal": "w" }, { "literal": "i" }, { "literal": "l" }, { "literal": "l" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "will_you$subexpression$1", "symbols": ["will_you$subexpression$1$string$1"] },
            { "name": "will_you$subexpression$1$string$2", "symbols": [{ "literal": "c" }, { "literal": "a" }, { "literal": "n" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "will_you$subexpression$1", "symbols": ["will_you$subexpression$1$string$2"] },
            { "name": "will_you$subexpression$1$string$3", "symbols": [{ "literal": "c" }, { "literal": "o" }, { "literal": "u" }, { "literal": "l" }, { "literal": "d" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "will_you$subexpression$1", "symbols": ["will_you$subexpression$1$string$3"] },
            { "name": "will_you$string$1", "symbols": [{ "literal": "y" }, { "literal": "o" }, { "literal": "u" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "will_you", "symbols": ["will_you$subexpression$1", "will_you$string$1"] },
            { "name": "please$string$1", "symbols": [{ "literal": "p" }, { "literal": "l" }, { "literal": "e" }, { "literal": "a" }, { "literal": "s" }, { "literal": "e" }], "postprocess": function (d) { return d.join(''); } },
            { "name": "please", "symbols": ["please$string$1"] }
        ],
        ParserStart: "main"
    };
});
